export const FETCH_DATASET_START = 'FETCH_DATASET_START';
export const FETCH_DATASET_SUCCESS = 'FETCH_DATASET_SUCCESS';
export const FETCH_DATASET_FAIL = 'FETCH_DATASET_FAIL';

export const FETCH_DATASET_INFO_START = 'FETCH_DATASET_INFO_START';
export const FETCH_DATASET_INFO_SUCCESS = 'FETCH_DATASET_INFO_SUCCESS';
export const FETCH_DATASET_INFO_FAIL = 'FETCH_DATASET_INFO_FAIL';

export const FETCH_CONCEPT_INFO_START = 'FETCH_CONCEPT_INFO_START';
export const FETCH_CONCEPT_INFO_SUCCESS = 'FETCH_CONCEPT_INFO_SUCCESS';
export const FETCH_CONCEPT_INFO_FAIL = 'FETCH_CONCEPT_INFO_FAIL';

export const FETCH_SLICE_INFO_START = 'FETCH_SLICE_INFO_START';
export const FETCH_SLICE_INFO_SUCESS = 'FETCH_SLICE_INFO_SUCESS';
export const FETCH_SLICE_INFO_FAIL = 'FETCH_SLICE_INFO_FAIL';

export const QUERY_SLICE_START = 'QUERY_SLICE_START';
export const QUERY_SLICE_SUCCESS = 'QUERY_SLICE_SUCCESS';
export const QUERY_SLICE_FAIL = 'QUERY_SLICE_FAIL';

